import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { TRPCReactProvider } from "@/trpc/react";
import { ToastContainer, Bounce } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import { WeatherProvider } from '@/app/(protected)/context/WeatherContext';
import { ClientProvider } from '@/components/ClientProvider';

export const metadata: Metadata = {
  title: "EcoTrack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <ClientProvider>
        {/* <WeatherProvider> */}
          <html lang="en" className={`${GeistSans.variable} dark`}>
            <body>
              <TRPCReactProvider>{children}</TRPCReactProvider>
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
                transition={Bounce}
                progressClassName="toast-progress"
              />
            </body>
          </html>
        {/* </WeatherProvider> */}
      </ClientProvider>
    </ClerkProvider>
  );
}